image: wcrum/imageshift

# gets sent to be a configmap
config: imageswap.yaml

mutatingwebhook:
  certmanager: true

  existing-secret: my-secret

  cert: #base64 encoded crt.pem
  key:  #base64 encoded key.pem


injectSecrets:
  enabled: true
  credential: #base64 encoded secret