apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-annotate-webhook
  labels:
    app: pod-annotate-webhook
    kind: mutator
webhooks:
  - name: pod-annotate-webhook.slok.dev
    sideEffects: None
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: pod-annotate-webhook
        namespace: sandbox
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURzakNDQXBxZ0F3SUJBZ0lSQU56TXovRzVhK0RzYU1UNkhFT1dzVUV3RFFZSktvWklodmNOQVFFTEJRQXcKTFRFVk1CTUdBMVVFQ2hNTVkyVnlkQzF0WVc1aFoyVnlNUlF3RWdZRFZRUURFd3RsZUdGdGNHeGxMbU52YlRBZQpGdzB5TkRFd01qQXdOalF5TURkYUZ3MHlOVEF4TVRnd05qUXlNRGRhTUMweEZUQVRCZ05WQkFvVERHTmxjblF0CmJXRnVZV2RsY2pFVU1CSUdBMVVFQXhNTFpYaGhiWEJzWlM1amIyMHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUEKQTRJQkR3QXdnZ0VLQW9JQkFRRE9FUkNOZ1BEZG9JbnpFUFAwdkxIV1dhL1p0MWdtVnRDd3ZLYmdwK0FMcEFKZgphMGxZVG1zN2dmRjNUd21YRml5b0dFRTBoNyt1WUFKTTNyOURlRWpsa1M1TlpDY3M0WXdZeU5NcDVJNHZ3eDVKCmpBdmtlR1UyUmlCazNXbFV5S01FQWJNU0IwTitubitJbGJ2bkduSXh6SzZ5K1dIL1l1ZDR5amFVcHRkcnI4MjUKeldSaHFpQWlqOCt1YlJGRHpQWVpEcG1TOXozMHJwUHBwZndUbTdOZDRYam9ZM0J6TElJRU1HRVRpb3lDNFpxdwo0a296a083YW1iTG93aklWSjFlaUdjaUFPZUtIVXNLb25leXQrdytycUVadWp0Sm4rcHZUaVhsVm5oOVMvMmFXCmgxSzZUVG1qYmpqeE9ickt4dWZLTGJlVnFmeHlDVS95Y2k5MFpOQzdBZ01CQUFHamdjd3dnY2t3SFFZRFZSMGwKQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd2daa0dBMVVkRVFTQgprVENCam9JTFpYaGhiWEJzWlM1amIyMkNEM2QzZHk1bGVHRnRjR3hsTG1OdmJZSWdjRzlrTFdGdWJtOTBZWFJsCkxYZGxZbWh2YjJzdWMyRnVaR0p2ZUM1emRtT0JHR3B2YUc0dVpHOWxRR05sY25RdGJXRnVZV2RsY2k1cGI0Y0UKd0tnQUJZWXNjM0JwWm1abE9pOHZZMngxYzNSbGNpNXNiMk5oYkM5dWN5OXpZVzVrWW05NEwzTmhMMlY0WVcxdwpiR1V3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUR1OW11TCtCemZLMjFnWWt2blIzM3ZrUSs5UHVNdStJZVN6Ck5qK1NqeS9aRndMQ2orOUJhRGQ1Q3lNOFc3dVZrdmx2MDZ3QkRjZVF5WXZZUmorYjhqQlkzWFFnbDJkV2pVT28Kc1IrcXBhWnZjOWRlWmxPUXNYNHhha0dNR3BFZmd2V1RhTWlLUmF5cFNFeEVWS1pHK2RxdW16R1QzVnVKZ3NVYgowcG9XRjRPakoxRUNSbjNGdmhyY0k0KzZ6c01TTEU1U3ZtV1lITHBwdlBvSVZrczZkajVlbnVYNGsxMy82YldtClU3QUQzZ1lDUFhob2pCREFDU1dWUGFyL1d4WTM0NFEvUEg4Z1VFeGlPSzB1c0dRNlRMWUhldG1ZRHJiSXZ1Q28KaDhLZ001dkVHVURFVE9FeGlhTEVQQTRWWTNtNHRBbVlBVGVYaG01UUhhdmxJNHZOTGgwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    matchConditions:
      - name: "exclude-imageswap"
        expression: '!(request.namespace == "sandbox")'