apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: imageshift-webhook
  labels:
    app: imageshift-webhook
    kind: mutator
webhooks:
  - name: imageshift-webhook.wcrum.dev
    sideEffects: None
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: imageshift-webhook
        namespace: sandbox
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURzakNDQXBxZ0F3SUJBZ0lSQUxFNXgxY1gwQUR4N1pnZitSYXJMMnN3RFFZSktvWklodmNOQVFFTEJRQXcKTFRFVk1CTUdBMVVFQ2hNTVkyVnlkQzF0WVc1aFoyVnlNUlF3RWdZRFZRUURFd3RsZUdGdGNHeGxMbU52YlRBZQpGdzB5TkRFd016QXdNRFF4TURoYUZ3MHlOVEF4TWpnd01EUXhNRGhhTUMweEZUQVRCZ05WQkFvVERHTmxjblF0CmJXRnVZV2RsY2pFVU1CSUdBMVVFQXhNTFpYaGhiWEJzWlM1amIyMHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUEKQTRJQkR3QXdnZ0VLQW9JQkFRRGlMd2FubU8zN3hWeGpMd0g4d1dmYzAzemoyNS9jQmMrVzBBWFBQTzJnTnViVAp6RjlZS2hwaEFpanIwUW11S3Yxb0lZeDlsL0FmOVB5V0F1Qk9UUk9BckpGWkdOR3Q2Y204V3JuR3VVckZRWnpUCjFNM240SHErbkx4UEduaitjOTlHNkNIUXRNWjBMRko5aE9QOVhnZjE4aGMvUnQvNVVlMHVHWjYyRDVnTGxLMFQKRnAvQ3RZWE5vS09oY3cyQXJSSnl0VUh2RzA4Y0s4TDRKb0huTDNONEFPQi9Cd0l3QkpCa2NFY3grYzVYMWdiQwptSFRmTUgwa3h3b01ZZU5LT3o5b0t6SDUyVXc1K2RlVVZpcTlwZko5UjB6UXJrQW5ZL2ZCSkR4Qm5wbkFXY2pyCjkxVkd0OXZxT1lxbjU5NW9wbUdHbC9qb2VSUG9yRDQzMWtwdlozTmhBZ01CQUFHamdjd3dnY2t3SFFZRFZSMGwKQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd2daa0dBMVVkRVFTQgprVENCam9JTFpYaGhiWEJzWlM1amIyMkNEM2QzZHk1bGVHRnRjR3hsTG1OdmJZSWdjRzlrTFdGdWJtOTBZWFJsCkxYZGxZbWh2YjJzdWMyRnVaR0p2ZUM1emRtT0JHR3B2YUc0dVpHOWxRR05sY25RdGJXRnVZV2RsY2k1cGI0Y0UKd0tnQUJZWXNjM0JwWm1abE9pOHZZMngxYzNSbGNpNXNiMk5oYkM5dWN5OXpZVzVrWW05NEwzTmhMMlY0WVcxdwpiR1V3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUQ3WkxyYWZ5TjFLMWs3Tkw5Y2pwS3dSdUZPQlh5cHhjZGhiClU5N2ljd2J6TFc0QlVBWEVzOWJhNGErUUNGUVVjZjlEbld3UmZWSktsb0FRbUhYVW9rbWplRENGalliYmN6bXcKYlVFUkFhNk92MUQwOFFmMSswODhQMUI3MEZJejRvV1VVdGRJaWlJU0U4TmsyaHgxbFpDNzBoZStpcm51T09UWApETy85S1UzQlo1ZEZEVTg2MW1kcjF0U2FBYXl6VGZlTmhmQXNsakZVR2dMd2NUa0pMeGhRWmx6b1o0OWJmbWN6CjQybkdnQ0xCTzZYbEJsSnVCTlZjQXdXdTY3SlBLQW82RWRIUy96K1lSRzlTeDBPdG5iR2N5ZVorcHBVYVZNZVUKWkxGVXgwMEVVTVhwajB2Y1pBdXlvaVdEMi9YOU1lSDlTS2JpbVBETEZNSm8zMWo5cjBJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    matchConditions:
      - name: "exclude-imageswap"
        expression: '!(request.namespace == "sandbox")'