apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageshift-webhook
  labels:
    app: imageshift-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageshift-webhook
  template:
    metadata:
      labels:
        app: imageshift-webhook
    spec:
      serviceAccountName: imageshift-init-sa
      initContainers:
        - name: imageshift-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./main"]
          args: ["init"]
          env:
          - name: TLS_CERT_FILE
            value: /etc/webhook/tls.crt
          - name: TLS_KEY_FILE
            value: /etc/webhook/tls.key
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook
              readOnly: true
      containers:
        - name: imageshift-webhook
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./main"]
          args: ["webhook"]
          env:
          - name: TLS_CERT_FILE
            value: /etc/webhook/tls.crt
          - name: TLS_KEY_FILE
            value: /etc/webhook/tls.key
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook
              readOnly: true
            - name: imageswap-config
              mountPath: /etc/imageswap-config
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: example-com-tls
        - name: imageswap-config
          configMap:
            name: imageswap-config